name: Release to Homebrew Tap

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set version
        id: vars
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Download GitHub Tarball
        run: |
          VERSION=${GITHUB_REF_NAME}
          curl -sL "https://github.com/spicydev/heic-batch/archive/refs/tags/${VERSION}.tar.gz" -o heic-batch.tar.gz

      - name: Compute SHA256
        id: sha
        run: |
          echo "sha=$(shasum -a 256 heic-batch.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew tools repo
        uses: actions/checkout@v4
        with:
          repository: spicydev/homebrew-tools
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: tap

      - name: Update Homebrew formula
        run: |
          VERSION=${GITHUB_REF_NAME}
          SHA=${{ steps.sha.outputs.sha }}

          ls -l
          FILE=tap/Formula/heic-batch.rb

          sed -i '' 's|url ".*"|url "https://github.com/spicydev/heic-batch/archive/refs/tags/'"${VERSION}"'.tar.gz"|' "$FILE"
          sed -i '' 's/version ".*"/version "'"${VERSION#v}"'"/' "$FILE"
          sed -i '' 's/sha256 ".*"/sha256 "'"${SHA}"'"/' "$FILE"

      - name: Commit and push formula update
        run: |
          cd tap
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Formula/heic-batch.rb
          git commit -m "Update heic-batch to ${GITHUB_REF_NAME}" || echo "No changes"
          git push