name: Release to Homebrew Tap

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Set version
        id: vars
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Create tarball
        run: |
          VERSION=${GITHUB_REF_NAME}
          git archive --format=tar.gz --output heic-batch.tar.gz HEAD

      - name: Compute SHA256
        id: sha
        run: |
          echo "sha=$(shasum -a 256 heic-batch.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Checkout Homebrew tap repo
        uses: actions/checkout@v4
        with:
          repository: spicydev/homebrew-tools
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: Formula

      - name: Update Homebrew formula
        run: |
          VERSION=${GITHUB_REF_NAME}
          SHA=${{ steps.sha.outputs.sha }}

          FILE=heic-batch.rb

          sed -i '' "s/{{VERSION}}/${VERSION#v}/g" "$FILE"
          sed -i '' "s/{{SHA256}}/${SHA}/g" "$FILE"

      - name: Commit and push formula update
        run: |
          cd tap
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Formula/heic-batch.rb
          git commit -m "Update heic-batch to ${GITHUB_REF_NAME}" || echo "No changes"
          git push